add roxygen documentation to num_dist_scatter function
UBC-MDS/R_Prelim_Eda_Helper pull request #13
Opened 2023-01-18 05:55 UTC by austin-shih

2023-01-18 17:11 UTC, morrismanfung requested changes
I think it will be better if we keep the argument names same as the one standardized by @Lorraine97 in the python package.

2023-01-19 21:27 UTC, austin-shih reviewed
Aren't these the same? I'm looking in the python package and they seem to have not changed yet. I'll be making changes to the arguments as well so this isn't really important at the moment, just need something in there for now.

2023-01-19 22:17 UTC, morrismanfung commented
Variable names are changed in the main branch already. https://github.com/UBC-MDS/prelim_eda_helper/blob/main/src/prelim_eda_helper/prelim_eda_helper.py

Let's merge it first for this milestone.

2023-01-19 22:17 UTC, morrismanfung approved these changes

2023-01-20 08:12 UTC, merged